---
title: "Data Import"
output: github_document
---

```{r, setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

## relative path in Rproject starts where you create the project 

Read in the litters dataset
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
# ./ means starts from my project folder
litters_df = janitor::clean_names(litters_df)
# in the janitor package, call this function. This keeps from loading the whole janitor package
```

## Take a look at the data

Printing in the console
```{r}
litters_df
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
# View() function is often used directly in the console
```

## Options to read_csv
```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)
# this command skips row 10 and omit all the column names
litters_df = read_csv("./data/FAS_litters.csv", na = c(999,"","NA",","))
# transform elements in the dataset as empty, 999, "," or NA to missing values
```

## Read other file formats

Read xlsx file

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
?read_excel
```

Read in SAS file

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
pulse_df = janitor::clean_names(pulse_df)
pulse_df
```

## Comparison with Base R

What about read.csv?
```{r}
litters_df2 = read.csv("./data/FAS_litters.csv")
# litters_df using read_csv output the data format better
```







