---
title: "Data Manipulation"
output: github_document
---

```{r, setup}
#use option+command+i to get the rcode chunk
library(tidyverse)
```

## load FAS litters data
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others
```{r}
select(litters_df,group,litter_number)
select(litters_df,group,gd0_weight:gd_of_birth)
#specify a range of columns
```

```{r}
select(litters_df,-litter_number)
# only get rid of litter_number variable
```

Renaming columns
```{r}
select(litters_df,GROUP = group, LITTer_NUmber = litter_number)
#select and rename certain columns
```

```{r}
rename(litters_df,GROUP = group, LITTer_NUmber = litter_number)
# Rename columns and also keep other variables
```

```{r}
select(litters_df, starts_with("gd"))
# select with every variable with name begins with gd
```

```{r}
select(litters_df, litter_number, everything())
# move litter_number forward and other variables in sequence
```

```{r}
relocate(litters_df,litter_number)
#same as above operation
```

##  `filter`
operate on rows

```{r}
filter(litters_df,gd0_weight < 22)
#filter out rows based on the specified condition
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
# filter out everythin observations with the negate condition
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
# two more conditions
```

```{r}
filter(litters_df, group == "Con7")
filter(litters_df, group %in% c("Con7", "Mod8"))
# filter out either con7 or mod8
```

## `mutate`

Create additional variables or modify variables

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
# add a varaible and overwrite a variable by changing every letter to lower case
```


## `arrange`

Put things in order

```{r}
arrange(litters_df,pups_born_alive, gd0_weight)
# first sort by pups_alive, and within each level, sort gd0
```

## `%>%`

```{r}
litters_df_raw = read_csv("./data/FAS_litters.csv")
litters_df_clean = janitor::clean_names(litters_df_raw)
litters_df_selected = select(litters_df_clean,-pups_survive)
litters_mutated = mutate(litters_df_selected, wt_gain = gd18_weight - gd0_weight)
litters_wo_missing = drop_na(litters_mutated, gd0_weight)
# get rid of every observation where the gd0weight is missing
```

Use the Pipe operator instead

```{r}
# use shift+command+m to get the pipe line
litters_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
```







