---
title: "Tidy data"
output: github_document
---

```{r, setup}
library(tidyverse)
```

## `pivot_longer`

load the PULSE data
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()

pulse_data
```

```{r}
#columns too wide, need to make longer
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
pulse_data_tidy

# 4 observations for id 1003 and each value assigned to different levels of visit.
# bid_score_xx is too redundant. can use mutate, but in this case, add a line in the pivot_longer function: names_prefix
```

rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id,visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
# rewrite visit variable with everthing as bl to 00m
pulse_data
```

## `pivot_wider`

Make up some data
```{r}
result = 
  tibble(
    group = c("treatment", "treatment", "placebo","placebo"),
    time = c("pre","post","pre","post"),
    mean = c(4,8,3.5,4)
  )

result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

## Binding rows using Lord of the Rings

First, import each table
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "f3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```

Bind all the rows together

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring,two_towers,return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
# now need to make column names into observations of a variable
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```



